name: Publish as npm module
on:
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/

      - name: Install AJV-CLI
        run: npm install -g ajv-cli

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
