name: Build and Test on PR
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
        run: npm install -g ajv-cli

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Test
        run: npm run build:test; npm run test
